"""Add doctor_code to User model

Revision ID: 6002d4e6023b
Revises: d7d3a12fc4ab
Create Date: 2025-06-26 23:42:06.672599

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6002d4e6023b'
down_revision: Union[str, None] = 'd7d3a12fc4ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doctor_code', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_doctor_code'), 'users', ['doctor_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_doctor_code'), table_name='users')
    op.drop_column('users', 'doctor_code')
    # ### end Alembic commands ###
