"""Add doctor_id to User model for patient-doctor relationship

Revision ID: e9e33ff18978
Revises: 6002d4e6023b
Create Date: 2025-06-27 00:46:49.115302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9e33ff18978'
down_revision: Union[str, None] = '6002d4e6023b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['doctor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'doctor_id')
    # ### end Alembic commands ###
